CREATE TABLE IF NOT EXISTS theatres (
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	capacity INTEGER NOT NULL,
	room_id TEXT NOT NULL,
	created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
)