CREATE TABLE IF NOT EXISTS theatres (
	id SERIAL PRIMARY KEY,
	name TEXT UNIQUE NOT NULL,
	capacity INTEGER NOT NULL,
	room_id TEXT UNIQUE NOT NULL,
	created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
)
