CREATE TABLE IF NOT EXISTS reservations (
	id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL REFERENCES users(id),
	showtime_id INTEGER NOT NULL REFERENCES showtime(id),
	seat_number INTEGER UNIQUE NOT NULL,
	created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
)
